win:
	g++.exe -fdiagnostics-color=always -I./include ./src/main.cpp ./src/glad.c -o ./build/main.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/main.exe

linux:
	g++ -fdiagnostics-color=always -I./include ./src/main.cpp ./src/glad.c -o ./build/main -Llib -lglfw -lGL -lXrandr -lX11 -lrt -ldl
	./build/main

lab2:
	g++.exe -fdiagnostics-color=always -I./include ./src/lab2.cpp ./src/glad.c -o ./build/lab2.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/lab2.exe

lab3:
	g++.exe -fdiagnostics-color=always -I./include ./src/lab3.cpp ./src/glad.c -o ./build/lab3.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/lab3.exe