win:
	g++.exe -fdiagnostics-color=always -I./include ./src/main.cpp ./src/glad.c -o ./build/main.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/main.exe

linux:
	g++ -fdiagnostics-color=always -I./include ./src/main.cpp ./src/glad.c -o ./build/main -Llib -lglfw -lGL -lXrandr -lX11 -lrt -ldl
	./build/main

lab2:
	g++.exe -fdiagnostics-color=always -I./include ./src/lab2.cpp ./src/glad.c -o ./build/lab2.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/lab2.exe

lab3:
	g++.exe -fdiagnostics-color=always -I./include ./src/lab3.cpp ./src/glad.c -o ./build/lab3.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/lab3.exe
day_1_window:
	g++.exe -fdiagnostics-color=always -I./include ./src/day_1_window.cpp ./src/glad.c -o ./build/day_1_window.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/day_1_window.exe

day_2_full_colored:
	g++.exe -fdiagnostics-color=always -I./include ./src/day_2_full_colored.cpp ./src/glad.c -o ./build/day_2_full_colored.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/day_2_full_colored.exe

day_2_only_border:
	g++.exe -fdiagnostics-color=always -I./include ./src/day_2_only_border.cpp ./src/glad.c -o ./build/day_2_only_border.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/day_2_only_border.exe

day_2_red_colored:
	g++.exe -fdiagnostics-color=always -I./include ./src/day_2_red_colored.cpp ./src/glad.c -o ./build/day_2_red_colored.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/day_2_red_colored.exe

day_3_two_different_color:
	g++.exe -fdiagnostics-color=always -I./include ./src/day_3_two_different_color.cpp ./src/glad.c -o ./build/day_3_two_different_color.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/day_3_two_different_color.exe

day_4_dda:
	g++.exe -fdiagnostics-color=always -I./include ./src/day_4_dda.cpp ./src/glad.c -o ./build/day_4_dda.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/day_4_dda.exe
lab4:
	g++.exe -fdiagnostics-color=always -I./include ./src/lab4.cpp ./src/glad.c -o ./build/lab4.exe -Llib -lglfw3 -lopengl32 -lgdi32
	./build/lab4.exe